# Generated by Django 4.2.7 on 2023-12-09 04:18

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('encrypted_gender', django_cryptography.fields.encrypt(models.BooleanField(default=False))),
                ('encrypted_age', django_cryptography.fields.encrypt(models.IntegerField(default=0))),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('healthHistory', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=64)),
            ],
        ),
    ]
