# Generated by Django 4.2.7 on 2023-12-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
    ]
