# Generated by Django 4.2.7 on 2023-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='encrypted_age',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='encrypted_gender',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
