# Generated by Django 4.2.7 on 2023-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_health_encrypted_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='encrypted_age',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='encrypted_gender',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
